In [1]:
import numpy as np

In [4]:
array = np.array([1,2,3,4,5])


In [5]:
print(type(array))
print(type(array[0]))
print(array.dtype)

<class 'numpy.ndarray'>
<class 'numpy.int64'>
int64


In [8]:
array_multi = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(array_multi)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [13]:
#Array del 0 al 9 
print(np.arange(10))

#del 0 al 9 con saltos de 2
print(np.arange(0,10,2))
#Arra de 0 al 10, con saltos de 0,5
print(np.arange(0,10,0.5))
#Especificando el tipo de daro
print(np.arange(0,10,2, np.float64))

[0 1 2 3 4 5 6 7 8 9]
[0 2 4 6 8]
[0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5 5.  5.5 6.  6.5 7.  7.5 8.  8.5
 9.  9.5]
[0. 2. 4. 6. 8.]


In [22]:
print(np.random.rand(10))
#Matriz de numeros aleatorios
print(np.random.randint(5, size= (3,4)))
#Unidimensional
print(np.random.randint(5,10, size = 10))

[0.09381014 0.29256787 0.17963366 0.42853142 0.83969097 0.3189218
 0.98037293 0.85188732 0.9761932  0.3608636 ]
[[3 3 0 3]
 [4 2 1 3]
 [3 0 3 2]]
[9 5 7 7 7 8 7 6 8 6]
